// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.WebviewWindowOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function CreateWindow(options) {
    return $Call.ByID(544970000, options);
}

/**
 * @param {$models.MessageDialogOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function Dialog(options) {
    return $Call.ByID(1603189224, options);
}

/**
 * @param {string} name
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function EnableWindow(name, enabled) {
    return $Call.ByID(3477006231, name, enabled);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function Hello() {
    return $Call.ByID(1531277936);
}
