// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class UpdateEvent {
    /**
     * Creates a new UpdateEvent instance.
     * @param {Partial<UpdateEvent>} [$$source = {}] - The source object to create the UpdateEvent.
     */
    constructor($$source = {}) {
        if (!("eventID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventID"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateEvent(/** @type {Partial<UpdateEvent>} */($$parsedSource));
    }
}
