// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

export class MessageDialogOptions {
    /**
     * Creates a new MessageDialogOptions instance.
     * @param {Partial<MessageDialogOptions>} [$$source = {}] - The source object to create the MessageDialogOptions.
     */
    constructor($$source = {}) {
        if (!("DialogType" in $$source)) {
            /**
             * Info|Question|Warning|Error
             * @member
             * @type {string}
             */
            this["DialogType"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageDialogOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MessageDialogOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageDialogOptions(/** @type {Partial<MessageDialogOptions>} */($$parsedSource));
    }
}

export class UpdateEvent {
    /**
     * Creates a new UpdateEvent instance.
     * @param {Partial<UpdateEvent>} [$$source = {}] - The source object to create the UpdateEvent.
     */
    constructor($$source = {}) {
        if (!("eventID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventID"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateEvent}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateEvent(/** @type {Partial<UpdateEvent>} */($$parsedSource));
    }
}

export class WebviewWindowOptions {
    /**
     * Creates a new WebviewWindowOptions instance.
     * @param {Partial<WebviewWindowOptions>} [$$source = {}] - The source object to create the WebviewWindowOptions.
     */
    constructor($$source = {}) {
        if (!("Name" in $$source)) {
            /**
             * Name is a unique identifier that can be given to a window.
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Title" in $$source)) {
            /**
             * Title is the title of the window.
             * @member
             * @type {string}
             */
            this["Title"] = "";
        }
        if (!("Width" in $$source)) {
            /**
             * Width is the starting width of the window.
             * @member
             * @type {number}
             */
            this["Width"] = 0;
        }
        if (!("Height" in $$source)) {
            /**
             * Height is the starting height of the window.
             * @member
             * @type {number}
             */
            this["Height"] = 0;
        }
        if (!("AlwaysOnTop" in $$source)) {
            /**
             * AlwaysOnTop will make the window float above other windows.
             * @member
             * @type {boolean}
             */
            this["AlwaysOnTop"] = false;
        }
        if (!("URL" in $$source)) {
            /**
             * URL is the URL to load in the window.
             * @member
             * @type {string}
             */
            this["URL"] = "";
        }
        if (!("DisableResize" in $$source)) {
            /**
             * DisableResize will disable the ability to resize the window.
             * @member
             * @type {boolean}
             */
            this["DisableResize"] = false;
        }
        if (!("Frameless" in $$source)) {
            /**
             * Frameless will remove the window frame.
             * @member
             * @type {boolean}
             */
            this["Frameless"] = false;
        }
        if (!("MinWidth" in $$source)) {
            /**
             * MinWidth is the minimum width of the window.
             * @member
             * @type {number}
             */
            this["MinWidth"] = 0;
        }
        if (!("MinHeight" in $$source)) {
            /**
             * MinHeight is the minimum height of the window.
             * @member
             * @type {number}
             */
            this["MinHeight"] = 0;
        }
        if (!("MaxWidth" in $$source)) {
            /**
             * MaxWidth is the maximum width of the window.
             * @member
             * @type {number}
             */
            this["MaxWidth"] = 0;
        }
        if (!("MaxHeight" in $$source)) {
            /**
             * MaxHeight is the maximum height of the window.
             * @member
             * @type {number}
             */
            this["MaxHeight"] = 0;
        }
        if (!("StartState" in $$source)) {
            /**
             * StartState indicates the state of the window when it is first shown.
             * Default: WindowStateNormal
             * WindowStateNormal|WindowStateMinimised|WindowStateMaximised|WindowStateFullscreen
             * @member
             * @type {string}
             */
            this["StartState"] = "";
        }
        if (!("BackgroundType" in $$source)) {
            /**
             * BackgroundType is the type of background to use for the window.
             * Default: BackgroundTypeSolid
             * BackgroundTypeSolid|BackgroundTypeTransparent|BackgroundTypeTranslucent
             * @member
             * @type {string}
             */
            this["BackgroundType"] = "";
        }
        if (!("BackgroundColour" in $$source)) {
            /**
             * BackgroundColour is the colour to use for the window background.
             * R G B A
             * @member
             * @type {number[]}
             */
            this["BackgroundColour"] = Array.from({ length: 4 }, () => 0);
        }
        if (!("HTML" in $$source)) {
            /**
             * HTML is the HTML to load in the window.
             * @member
             * @type {string}
             */
            this["HTML"] = "";
        }
        if (!("JS" in $$source)) {
            /**
             * JS is the JavaScript to load in the window.
             * @member
             * @type {string}
             */
            this["JS"] = "";
        }
        if (!("CSS" in $$source)) {
            /**
             * CSS is the CSS to load in the window.
             * @member
             * @type {string}
             */
            this["CSS"] = "";
        }
        if (!("InitialPosition" in $$source)) {
            /**
             * Initial Position
             * WindowCentered|WindowXY
             * @member
             * @type {string}
             */
            this["InitialPosition"] = "";
        }
        if (!("X" in $$source)) {
            /**
             * X is the starting X position of the window.
             * @member
             * @type {number}
             */
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            /**
             * Y is the starting Y position of the window.
             * @member
             * @type {number}
             */
            this["Y"] = 0;
        }
        if (!("Hidden" in $$source)) {
            /**
             * Hidden will hide the window when it is first created.
             * @member
             * @type {boolean}
             */
            this["Hidden"] = false;
        }
        if (!("Zoom" in $$source)) {
            /**
             * Zoom is the zoom level of the window.
             * @member
             * @type {number}
             */
            this["Zoom"] = 0;
        }
        if (!("ZoomControlEnabled" in $$source)) {
            /**
             * ZoomControlEnabled will enable the zoom control.
             * @member
             * @type {boolean}
             */
            this["ZoomControlEnabled"] = false;
        }
        if (!("EnableFileDrop" in $$source)) {
            /**
             * EnableFileDrop enables drag and drop of files onto the window.
             * When enabled, files dragged from the OS onto elements with the
             * `data-file-drop-target` attribute will trigger a FilesDropped event.
             * @member
             * @type {boolean}
             */
            this["EnableFileDrop"] = false;
        }
        if (!("OpenInspectorOnStartup" in $$source)) {
            /**
             * OpenInspectorOnStartup will open the inspector when the window is first shown.
             * @member
             * @type {boolean}
             */
            this["OpenInspectorOnStartup"] = false;
        }
        if (!("Mac" in $$source)) {
            /**
             * Mac options
             * @member
             * @type {application$0.MacWindow}
             */
            this["Mac"] = (new application$0.MacWindow());
        }
        if (!("Windows" in $$source)) {
            /**
             * Windows options
             * @member
             * @type {application$0.WindowsWindow}
             */
            this["Windows"] = (new application$0.WindowsWindow());
        }
        if (!("Linux" in $$source)) {
            /**
             * Linux options
             * @member
             * @type {application$0.LinuxWindow}
             */
            this["Linux"] = (new application$0.LinuxWindow());
        }
        if (!("MinimiseButtonState" in $$source)) {
            /**
             * Toolbar button states
             * ButtonEnabled|ButtonDisabled|ButtonHidden
             * @member
             * @type {string}
             */
            this["MinimiseButtonState"] = "";
        }
        if (!("MaximiseButtonState" in $$source)) {
            /**
             * ButtonEnabled|ButtonDisabled|ButtonHidden
             * @member
             * @type {string}
             */
            this["MaximiseButtonState"] = "";
        }
        if (!("CloseButtonState" in $$source)) {
            /**
             * ButtonEnabled|ButtonDisabled|ButtonHidden
             * @member
             * @type {string}
             */
            this["CloseButtonState"] = "";
        }
        if (!("DevToolsEnabled" in $$source)) {
            /**
             * If true, the window's devtools will be available (default true in builds without the `production` build tag)
             * @member
             * @type {boolean}
             */
            this["DevToolsEnabled"] = false;
        }
        if (!("DefaultContextMenuDisabled" in $$source)) {
            /**
             * If true, the window's default context menu will be disabled (default false)
             * @member
             * @type {boolean}
             */
            this["DefaultContextMenuDisabled"] = false;
        }
        if (!("IgnoreMouseEvents" in $$source)) {
            /**
             * IgnoreMouseEvents will ignore mouse events in the window (Windows + Mac only)
             * @member
             * @type {boolean}
             */
            this["IgnoreMouseEvents"] = false;
        }
        if (!("ContentProtectionEnabled" in $$source)) {
            /**
             * ContentProtectionEnabled specifies whether content protection is enabled, preventing screen capture and recording.
             * Effective on Windows and macOS only; no-op on Linux.
             * Best-effort protection with platform-specific caveats (see docs).
             * @member
             * @type {boolean}
             */
            this["ContentProtectionEnabled"] = false;
        }
        if (!("HideOnFocusLost" in $$source)) {
            /**
             * HideOnFocusLost will hide the window when it loses focus.
             * Useful for popup/transient windows like systray attached windows.
             * On Linux with focus-follows-mouse WMs (Hyprland, Sway, i3), this is automatically disabled
             * as it would cause the window to hide immediately when the mouse moves away.
             * @member
             * @type {boolean}
             */
            this["HideOnFocusLost"] = false;
        }
        if (!("HideOnEscape" in $$source)) {
            /**
             * HideOnEscape will hide the window when the Escape key is pressed.
             * Useful for popup/transient windows that should dismiss on Escape.
             * @member
             * @type {boolean}
             */
            this["HideOnEscape"] = false;
        }
        if (!("UseApplicationMenu" in $$source)) {
            /**
             * UseApplicationMenu indicates this window should use the application menu
             * set via app.Menu.Set() instead of requiring a window-specific menu.
             * On macOS this has no effect as the application menu is always global.
             * On Windows/Linux, if true and no explicit window menu is set, the window
             * will use the application menu. Defaults to false for backwards compatibility.
             * @member
             * @type {boolean}
             */
            this["UseApplicationMenu"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WebviewWindowOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WebviewWindowOptions}
     */
    static createFrom($$source = {}) {
        const $$createField26_0 = $$createType0;
        const $$createField27_0 = $$createType1;
        const $$createField28_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Mac" in $$parsedSource) {
            $$parsedSource["Mac"] = $$createField26_0($$parsedSource["Mac"]);
        }
        if ("Windows" in $$parsedSource) {
            $$parsedSource["Windows"] = $$createField27_0($$parsedSource["Windows"]);
        }
        if ("Linux" in $$parsedSource) {
            $$parsedSource["Linux"] = $$createField28_0($$parsedSource["Linux"]);
        }
        return new WebviewWindowOptions(/** @type {Partial<WebviewWindowOptions>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = application$0.MacWindow.createFrom;
const $$createType1 = application$0.WindowsWindow.createFrom;
const $$createType2 = application$0.LinuxWindow.createFrom;
