//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../../changeme/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "InstallDriverEvent": $$createType0,
        "StatusBarEvent": $$createType1,
    }));
}

// Private type creation functions
const $$createType0 = main$0.InstallDriverEvent.createFrom;
const $$createType1 = main$0.StatusBarEvent.createFrom;

configure();
