// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as u$0 from "../../../../../leaanthony/u/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as events$0 from "../events/models.js";

/**
 * @readonly
 * @enum {number}
 */
export const BackdropType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    Auto: 0,
    None: 1,
    Mica: 2,
    Acrylic: 3,
    Tabbed: 4,
};

/**
 * @readonly
 * @enum {number}
 */
export const CoreWebView2PermissionKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    CoreWebView2PermissionKindUnknownPermission: 0,
    CoreWebView2PermissionKindMicrophone: 1,
    CoreWebView2PermissionKindCamera: 2,
    CoreWebView2PermissionKindGeolocation: 3,
    CoreWebView2PermissionKindNotifications: 4,
    CoreWebView2PermissionKindOtherSensors: 5,
    CoreWebView2PermissionKindClipboardRead: 6,
};

/**
 * @readonly
 * @enum {number}
 */
export const CoreWebView2PermissionState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    CoreWebView2PermissionStateDefault: 0,
    CoreWebView2PermissionStateAllow: 1,
    CoreWebView2PermissionStateDeny: 2,
};

/**
 * LinuxMenuStyle defines how the application menu is displayed on Linux (GTK4 only).
 * On GTK3 builds, this option is ignored and MenuBar style is always used.
 * @readonly
 * @enum {number}
 */
export const LinuxMenuStyle = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * LinuxMenuStyleMenuBar displays a traditional menu bar below the title bar (default)
     */
    LinuxMenuStyleMenuBar: 0,

    /**
     * LinuxMenuStylePrimaryMenu displays a primary menu button in the header bar (GNOME style)
     */
    LinuxMenuStylePrimaryMenu: 1,
};

/**
 * LinuxWindow specific to Linux windows
 */
export class LinuxWindow {
    /**
     * Creates a new LinuxWindow instance.
     * @param {Partial<LinuxWindow>} [$$source = {}] - The source object to create the LinuxWindow.
     */
    constructor($$source = {}) {
        if (!("Icon" in $$source)) {
            /**
             * Icon Sets up the icon representing the window. This icon is used when the window is minimized
             * (also known as iconified).
             * @member
             * @type {string}
             */
            this["Icon"] = "";
        }
        if (!("WindowIsTranslucent" in $$source)) {
            /**
             * WindowIsTranslucent sets the window's background to transparent when enabled.
             * @member
             * @type {boolean}
             */
            this["WindowIsTranslucent"] = false;
        }
        if (!("WebviewGpuPolicy" in $$source)) {
            /**
             * WebviewGpuPolicy used for determining the hardware acceleration policy for the webview.
             *   - WebviewGpuPolicyAlways
             *   - WebviewGpuPolicyOnDemand
             *   - WebviewGpuPolicyNever
             * 
             * Due to https://github.com/wailsapp/wails/issues/2977, if options.Linux is nil
             * in the call to wails.Run(), WebviewGpuPolicy is set by default to WebviewGpuPolicyNever.
             * Client code may override this behavior by passing a non-nil Options and set
             * WebviewGpuPolicy as needed.
             * @member
             * @type {WebviewGpuPolicy}
             */
            this["WebviewGpuPolicy"] = WebviewGpuPolicy.$zero;
        }
        if (!("WindowDidMoveDebounceMS" in $$source)) {
            /**
             * WindowDidMoveDebounceMS is the debounce time in milliseconds for the WindowDidMove event
             * @member
             * @type {number}
             */
            this["WindowDidMoveDebounceMS"] = 0;
        }
        if (!("Menu" in $$source)) {
            /**
             * Menu is the window's menu
             * @member
             * @type {Menu | null}
             */
            this["Menu"] = null;
        }
        if (!("MenuStyle" in $$source)) {
            /**
             * MenuStyle controls how the menu is displayed (GTK4 only, ignored on GTK3)
             * @member
             * @type {LinuxMenuStyle}
             */
            this["MenuStyle"] = LinuxMenuStyle.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinuxWindow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LinuxWindow}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $Create.ByteSlice;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Icon" in $$parsedSource) {
            $$parsedSource["Icon"] = $$createField0_0($$parsedSource["Icon"]);
        }
        if ("Menu" in $$parsedSource) {
            $$parsedSource["Menu"] = $$createField4_0($$parsedSource["Menu"]);
        }
        return new LinuxWindow(/** @type {Partial<LinuxWindow>} */($$parsedSource));
    }
}

/**
 * MacAppearanceType is a type of Appearance for Cocoa windows
 * @readonly
 * @enum {string}
 */
export const MacAppearanceType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * DefaultAppearance uses the default system value
     */
    DefaultAppearance: "",

    /**
     * NSAppearanceNameAqua - The standard light system appearance.
     */
    NSAppearanceNameAqua: "NSAppearanceNameAqua",

    /**
     * NSAppearanceNameDarkAqua - The standard dark system appearance.
     */
    NSAppearanceNameDarkAqua: "NSAppearanceNameDarkAqua",

    /**
     * NSAppearanceNameVibrantLight - The light vibrant appearance
     */
    NSAppearanceNameVibrantLight: "NSAppearanceNameVibrantLight",

    /**
     * NSAppearanceNameAccessibilityHighContrastAqua - A high-contrast version of the standard light system appearance.
     */
    NSAppearanceNameAccessibilityHighContrastAqua: "NSAppearanceNameAccessibilityHighContrastAqua",

    /**
     * NSAppearanceNameAccessibilityHighContrastDarkAqua - A high-contrast version of the standard dark system appearance.
     */
    NSAppearanceNameAccessibilityHighContrastDarkAqua: "NSAppearanceNameAccessibilityHighContrastDarkAqua",

    /**
     * NSAppearanceNameAccessibilityHighContrastVibrantLight - A high-contrast version of the light vibrant appearance.
     */
    NSAppearanceNameAccessibilityHighContrastVibrantLight: "NSAppearanceNameAccessibilityHighContrastVibrantLight",

    /**
     * NSAppearanceNameAccessibilityHighContrastVibrantDark - A high-contrast version of the dark vibrant appearance.
     */
    NSAppearanceNameAccessibilityHighContrastVibrantDark: "NSAppearanceNameAccessibilityHighContrastVibrantDark",
};

/**
 * MacBackdrop is the backdrop type for macOS
 * @readonly
 * @enum {number}
 */
export const MacBackdrop = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * MacBackdropNormal - The default value. The window will have a normal opaque background.
     */
    MacBackdropNormal: 0,

    /**
     * MacBackdropTransparent - The window will have a transparent background, with the content underneath it being visible
     */
    MacBackdropTransparent: 1,

    /**
     * MacBackdropTranslucent - The window will have a translucent background, with the content underneath it being "fuzzy" or "frosted"
     */
    MacBackdropTranslucent: 2,

    /**
     * MacBackdropLiquidGlass - The window will use Apple's Liquid Glass effect (macOS 15.0+ with fallback to translucent)
     */
    MacBackdropLiquidGlass: 3,
};

/**
 * MacLiquidGlass contains configuration for the Liquid Glass effect
 */
export class MacLiquidGlass {
    /**
     * Creates a new MacLiquidGlass instance.
     * @param {Partial<MacLiquidGlass>} [$$source = {}] - The source object to create the MacLiquidGlass.
     */
    constructor($$source = {}) {
        if (!("Style" in $$source)) {
            /**
             * Style of the glass effect
             * @member
             * @type {MacLiquidGlassStyle}
             */
            this["Style"] = MacLiquidGlassStyle.$zero;
        }
        if (!("Material" in $$source)) {
            /**
             * Material to use for NSVisualEffectView (when NSGlassEffectView is not available)
             * Set to NSVisualEffectMaterialAuto to use automatic selection based on Style
             * @member
             * @type {NSVisualEffectMaterial}
             */
            this["Material"] = NSVisualEffectMaterial.$zero;
        }
        if (!("CornerRadius" in $$source)) {
            /**
             * Corner radius for the glass effect (0 for square corners)
             * @member
             * @type {number}
             */
            this["CornerRadius"] = 0;
        }
        if (!("TintColor" in $$source)) {
            /**
             * Tint color for the glass (optional, nil for no tint)
             * @member
             * @type {RGBA | null}
             */
            this["TintColor"] = null;
        }
        if (!("GroupID" in $$source)) {
            /**
             * Group identifier for merging multiple glass windows
             * @member
             * @type {string}
             */
            this["GroupID"] = "";
        }
        if (!("GroupSpacing" in $$source)) {
            /**
             * Spacing between grouped glass elements (in points)
             * @member
             * @type {number}
             */
            this["GroupSpacing"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacLiquidGlass instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MacLiquidGlass}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TintColor" in $$parsedSource) {
            $$parsedSource["TintColor"] = $$createField3_0($$parsedSource["TintColor"]);
        }
        return new MacLiquidGlass(/** @type {Partial<MacLiquidGlass>} */($$parsedSource));
    }
}

/**
 * MacLiquidGlassStyle defines the style of the Liquid Glass effect
 * @readonly
 * @enum {number}
 */
export const MacLiquidGlassStyle = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * LiquidGlassStyleAutomatic - System determines the best style
     */
    LiquidGlassStyleAutomatic: 0,

    /**
     * LiquidGlassStyleLight - Light glass appearance
     */
    LiquidGlassStyleLight: 1,

    /**
     * LiquidGlassStyleDark - Dark glass appearance
     */
    LiquidGlassStyleDark: 2,

    /**
     * LiquidGlassStyleVibrant - Vibrant glass with enhanced effects
     */
    LiquidGlassStyleVibrant: 3,
};

/**
 * MacTitleBar contains options for the Mac titlebar
 */
export class MacTitleBar {
    /**
     * Creates a new MacTitleBar instance.
     * @param {Partial<MacTitleBar>} [$$source = {}] - The source object to create the MacTitleBar.
     */
    constructor($$source = {}) {
        if (!("AppearsTransparent" in $$source)) {
            /**
             * AppearsTransparent will make the titlebar transparent
             * @member
             * @type {boolean}
             */
            this["AppearsTransparent"] = false;
        }
        if (!("Hide" in $$source)) {
            /**
             * Hide will hide the titlebar
             * @member
             * @type {boolean}
             */
            this["Hide"] = false;
        }
        if (!("HideTitle" in $$source)) {
            /**
             * HideTitle will hide the title
             * @member
             * @type {boolean}
             */
            this["HideTitle"] = false;
        }
        if (!("FullSizeContent" in $$source)) {
            /**
             * FullSizeContent will extend the window content to the full size of the window
             * @member
             * @type {boolean}
             */
            this["FullSizeContent"] = false;
        }
        if (!("UseToolbar" in $$source)) {
            /**
             * UseToolbar will use a toolbar instead of a titlebar
             * @member
             * @type {boolean}
             */
            this["UseToolbar"] = false;
        }
        if (!("HideToolbarSeparator" in $$source)) {
            /**
             * HideToolbarSeparator will hide the toolbar separator
             * @member
             * @type {boolean}
             */
            this["HideToolbarSeparator"] = false;
        }
        if (!("ShowToolbarWhenFullscreen" in $$source)) {
            /**
             * ShowToolbarWhenFullscreen will keep the toolbar visible when the window is in fullscreen mode
             * @member
             * @type {boolean}
             */
            this["ShowToolbarWhenFullscreen"] = false;
        }
        if (!("ToolbarStyle" in $$source)) {
            /**
             * ToolbarStyle is the style of toolbar to use
             * @member
             * @type {MacToolbarStyle}
             */
            this["ToolbarStyle"] = MacToolbarStyle.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacTitleBar instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MacTitleBar}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MacTitleBar(/** @type {Partial<MacTitleBar>} */($$parsedSource));
    }
}

/**
 * MacToolbarStyle is the style of toolbar for macOS
 * @readonly
 * @enum {number}
 */
export const MacToolbarStyle = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * MacToolbarStyleAutomatic - The default value. The style will be determined by the window's given configuration
     */
    MacToolbarStyleAutomatic: 0,

    /**
     * MacToolbarStyleExpanded - The toolbar will appear below the window title
     */
    MacToolbarStyleExpanded: 1,

    /**
     * MacToolbarStylePreference - The toolbar will appear below the window title and the items in the toolbar will attempt to have equal widths when possible
     */
    MacToolbarStylePreference: 2,

    /**
     * MacToolbarStyleUnified - The window title will appear inline with the toolbar when visible
     */
    MacToolbarStyleUnified: 3,

    /**
     * MacToolbarStyleUnifiedCompact - Same as MacToolbarStyleUnified, but with reduced margins in the toolbar allowing more focus to be on the contents of the window
     */
    MacToolbarStyleUnifiedCompact: 4,
};

/**
 * MacWebviewPreferences contains preferences for the Mac webview
 */
export class MacWebviewPreferences {
    /**
     * Creates a new MacWebviewPreferences instance.
     * @param {Partial<MacWebviewPreferences>} [$$source = {}] - The source object to create the MacWebviewPreferences.
     */
    constructor($$source = {}) {
        if (!("TabFocusesLinks" in $$source)) {
            /**
             * TabFocusesLinks will enable tabbing to links
             * @member
             * @type {u$0.Bool}
             */
            this["TabFocusesLinks"] = (new u$0.Bool());
        }
        if (!("TextInteractionEnabled" in $$source)) {
            /**
             * TextInteractionEnabled will enable text interaction
             * @member
             * @type {u$0.Bool}
             */
            this["TextInteractionEnabled"] = (new u$0.Bool());
        }
        if (!("FullscreenEnabled" in $$source)) {
            /**
             * FullscreenEnabled will enable fullscreen
             * @member
             * @type {u$0.Bool}
             */
            this["FullscreenEnabled"] = (new u$0.Bool());
        }
        if (!("AllowsBackForwardNavigationGestures" in $$source)) {
            /**
             * AllowsBackForwardNavigationGestures enables horizontal swipe gestures for back/forward navigation
             * @member
             * @type {u$0.Bool}
             */
            this["AllowsBackForwardNavigationGestures"] = (new u$0.Bool());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacWebviewPreferences instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MacWebviewPreferences}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType4;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TabFocusesLinks" in $$parsedSource) {
            $$parsedSource["TabFocusesLinks"] = $$createField0_0($$parsedSource["TabFocusesLinks"]);
        }
        if ("TextInteractionEnabled" in $$parsedSource) {
            $$parsedSource["TextInteractionEnabled"] = $$createField1_0($$parsedSource["TextInteractionEnabled"]);
        }
        if ("FullscreenEnabled" in $$parsedSource) {
            $$parsedSource["FullscreenEnabled"] = $$createField2_0($$parsedSource["FullscreenEnabled"]);
        }
        if ("AllowsBackForwardNavigationGestures" in $$parsedSource) {
            $$parsedSource["AllowsBackForwardNavigationGestures"] = $$createField3_0($$parsedSource["AllowsBackForwardNavigationGestures"]);
        }
        return new MacWebviewPreferences(/** @type {Partial<MacWebviewPreferences>} */($$parsedSource));
    }
}

/**
 * MacWindow contains macOS specific options for Webview Windows
 */
export class MacWindow {
    /**
     * Creates a new MacWindow instance.
     * @param {Partial<MacWindow>} [$$source = {}] - The source object to create the MacWindow.
     */
    constructor($$source = {}) {
        if (!("Backdrop" in $$source)) {
            /**
             * Backdrop is the backdrop type for the window
             * @member
             * @type {MacBackdrop}
             */
            this["Backdrop"] = MacBackdrop.$zero;
        }
        if (!("DisableShadow" in $$source)) {
            /**
             * DisableShadow will disable the window shadow
             * @member
             * @type {boolean}
             */
            this["DisableShadow"] = false;
        }
        if (!("TitleBar" in $$source)) {
            /**
             * TitleBar contains options for the Mac titlebar
             * @member
             * @type {MacTitleBar}
             */
            this["TitleBar"] = (new MacTitleBar());
        }
        if (!("Appearance" in $$source)) {
            /**
             * Appearance is the appearance type for the window
             * @member
             * @type {MacAppearanceType}
             */
            this["Appearance"] = MacAppearanceType.$zero;
        }
        if (!("InvisibleTitleBarHeight" in $$source)) {
            /**
             * InvisibleTitleBarHeight defines the height of an invisible titlebar which responds to dragging
             * @member
             * @type {number}
             */
            this["InvisibleTitleBarHeight"] = 0;
        }
        if (!("EventMapping" in $$source)) {
            /**
             * Maps events from platform specific to common event types
             * @member
             * @type {{ [_ in events$0.WindowEventType]?: events$0.WindowEventType }}
             */
            this["EventMapping"] = {};
        }
        if (!("EnableFraudulentWebsiteWarnings" in $$source)) {
            /**
             * EnableFraudulentWebsiteWarnings will enable warnings for fraudulent websites.
             * Default: false
             * @member
             * @type {boolean}
             */
            this["EnableFraudulentWebsiteWarnings"] = false;
        }
        if (!("WebviewPreferences" in $$source)) {
            /**
             * WebviewPreferences contains preferences for the webview
             * @member
             * @type {MacWebviewPreferences}
             */
            this["WebviewPreferences"] = (new MacWebviewPreferences());
        }
        if (!("WindowLevel" in $$source)) {
            /**
             * WindowLevel sets the window level to control the order of windows in the screen
             * @member
             * @type {MacWindowLevel}
             */
            this["WindowLevel"] = MacWindowLevel.$zero;
        }
        if (!("CollectionBehavior" in $$source)) {
            /**
             * CollectionBehavior controls how the window behaves across macOS Spaces and fullscreen
             * @member
             * @type {MacWindowCollectionBehavior}
             */
            this["CollectionBehavior"] = MacWindowCollectionBehavior.$zero;
        }
        if (!("LiquidGlass" in $$source)) {
            /**
             * LiquidGlass contains configuration for the Liquid Glass effect
             * @member
             * @type {MacLiquidGlass}
             */
            this["LiquidGlass"] = (new MacLiquidGlass());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MacWindow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MacWindow}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        const $$createField5_0 = $$createType6;
        const $$createField7_0 = $$createType7;
        const $$createField10_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("TitleBar" in $$parsedSource) {
            $$parsedSource["TitleBar"] = $$createField2_0($$parsedSource["TitleBar"]);
        }
        if ("EventMapping" in $$parsedSource) {
            $$parsedSource["EventMapping"] = $$createField5_0($$parsedSource["EventMapping"]);
        }
        if ("WebviewPreferences" in $$parsedSource) {
            $$parsedSource["WebviewPreferences"] = $$createField7_0($$parsedSource["WebviewPreferences"]);
        }
        if ("LiquidGlass" in $$parsedSource) {
            $$parsedSource["LiquidGlass"] = $$createField10_0($$parsedSource["LiquidGlass"]);
        }
        return new MacWindow(/** @type {Partial<MacWindow>} */($$parsedSource));
    }
}

/**
 * MacWindowCollectionBehavior controls window behavior across macOS Spaces and fullscreen.
 * These correspond to NSWindowCollectionBehavior bitmask values and can be combined using bitwise OR.
 * For example: MacWindowCollectionBehaviorCanJoinAllSpaces | MacWindowCollectionBehaviorFullScreenAuxiliary
 * @readonly
 * @enum {number}
 */
export const MacWindowCollectionBehavior = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * MacWindowCollectionBehaviorDefault is zero value - when set, FullScreenPrimary is used for backwards compatibility
     */
    MacWindowCollectionBehaviorDefault: 0,

    /**
     * MacWindowCollectionBehaviorCanJoinAllSpaces allows window to appear on all Spaces
     * 1
     */
    MacWindowCollectionBehaviorCanJoinAllSpaces: 1,

    /**
     * MacWindowCollectionBehaviorMoveToActiveSpace moves window to active Space when shown
     * 2
     */
    MacWindowCollectionBehaviorMoveToActiveSpace: 2,

    /**
     * MacWindowCollectionBehaviorManaged is the default managed window behavior
     * 4
     */
    MacWindowCollectionBehaviorManaged: 4,

    /**
     * MacWindowCollectionBehaviorTransient marks window as temporary/transient
     * 8
     */
    MacWindowCollectionBehaviorTransient: 8,

    /**
     * MacWindowCollectionBehaviorStationary keeps window stationary during Space switches
     * 16
     */
    MacWindowCollectionBehaviorStationary: 16,

    /**
     * MacWindowCollectionBehaviorParticipatesInCycle includes window in Cmd+` cycling (default for normal windows)
     * 32
     */
    MacWindowCollectionBehaviorParticipatesInCycle: 32,

    /**
     * MacWindowCollectionBehaviorIgnoresCycle excludes window from Cmd+` cycling
     * 64
     */
    MacWindowCollectionBehaviorIgnoresCycle: 64,

    /**
     * MacWindowCollectionBehaviorFullScreenPrimary allows the window to enter fullscreen
     * 128
     */
    MacWindowCollectionBehaviorFullScreenPrimary: 128,

    /**
     * MacWindowCollectionBehaviorFullScreenAuxiliary allows window to overlay fullscreen apps
     * 256
     */
    MacWindowCollectionBehaviorFullScreenAuxiliary: 256,

    /**
     * MacWindowCollectionBehaviorFullScreenNone prevents window from entering fullscreen (macOS 10.7+)
     * 512
     */
    MacWindowCollectionBehaviorFullScreenNone: 512,

    /**
     * MacWindowCollectionBehaviorFullScreenAllowsTiling allows side-by-side tiling in fullscreen (macOS 10.11+)
     * 2048
     */
    MacWindowCollectionBehaviorFullScreenAllowsTiling: 2048,

    /**
     * MacWindowCollectionBehaviorFullScreenDisallowsTiling prevents tiling in fullscreen (macOS 10.11+)
     * 4096
     */
    MacWindowCollectionBehaviorFullScreenDisallowsTiling: 4096,
};

/**
 * @readonly
 * @enum {string}
 */
export const MacWindowLevel = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MacWindowLevelNormal: "normal",
    MacWindowLevelFloating: "floating",
    MacWindowLevelTornOffMenu: "tornOffMenu",
    MacWindowLevelModalPanel: "modalPanel",
    MacWindowLevelMainMenu: "mainMenu",
    MacWindowLevelStatus: "status",
    MacWindowLevelPopUpMenu: "popUpMenu",
    MacWindowLevelScreenSaver: "screenSaver",
};

export class Menu {
    /**
     * Creates a new Menu instance.
     * @param {Partial<Menu>} [$$source = {}] - The source object to create the Menu.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Menu instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Menu}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Menu(/** @type {Partial<Menu>} */($$parsedSource));
    }
}

export class MenuBarTheme {
    /**
     * Creates a new MenuBarTheme instance.
     * @param {Partial<MenuBarTheme>} [$$source = {}] - The source object to create the MenuBarTheme.
     */
    constructor($$source = {}) {
        if (!("Default" in $$source)) {
            /**
             * Default is the default theme
             * @member
             * @type {TextTheme | null}
             */
            this["Default"] = null;
        }
        if (!("Hover" in $$source)) {
            /**
             * Hover defines the theme to use when the menu item is hovered
             * @member
             * @type {TextTheme | null}
             */
            this["Hover"] = null;
        }
        if (!("Selected" in $$source)) {
            /**
             * Selected defines the theme to use when the menu item is selected
             * @member
             * @type {TextTheme | null}
             */
            this["Selected"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MenuBarTheme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MenuBarTheme}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType10;
        const $$createField1_0 = $$createType10;
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Default" in $$parsedSource) {
            $$parsedSource["Default"] = $$createField0_0($$parsedSource["Default"]);
        }
        if ("Hover" in $$parsedSource) {
            $$parsedSource["Hover"] = $$createField1_0($$parsedSource["Hover"]);
        }
        if ("Selected" in $$parsedSource) {
            $$parsedSource["Selected"] = $$createField2_0($$parsedSource["Selected"]);
        }
        return new MenuBarTheme(/** @type {Partial<MenuBarTheme>} */($$parsedSource));
    }
}

/**
 * NSVisualEffectMaterial represents the NSVisualEffectMaterial enum for macOS
 * @readonly
 * @enum {number}
 */
export const NSVisualEffectMaterial = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * NSVisualEffectMaterial values from macOS SDK
     */
    NSVisualEffectMaterialAppearanceBased: 0,
    NSVisualEffectMaterialLight: 1,
    NSVisualEffectMaterialDark: 2,
    NSVisualEffectMaterialTitlebar: 3,
    NSVisualEffectMaterialSelection: 4,
    NSVisualEffectMaterialMenu: 5,
    NSVisualEffectMaterialPopover: 6,
    NSVisualEffectMaterialSidebar: 7,
    NSVisualEffectMaterialHeaderView: 10,
    NSVisualEffectMaterialSheet: 11,
    NSVisualEffectMaterialWindowBackground: 12,
    NSVisualEffectMaterialHUDWindow: 13,
    NSVisualEffectMaterialFullScreenUI: 15,
    NSVisualEffectMaterialToolTip: 17,
    NSVisualEffectMaterialContentBackground: 18,
    NSVisualEffectMaterialUnderWindowBackground: 21,
    NSVisualEffectMaterialUnderPageBackground: 22,

    /**
     * Use auto-selection based on Style
     */
    NSVisualEffectMaterialAuto: -1,
};

export class RGBA {
    /**
     * Creates a new RGBA instance.
     * @param {Partial<RGBA>} [$$source = {}] - The source object to create the RGBA.
     */
    constructor($$source = {}) {
        if (!("Red" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Red"] = 0;
        }
        if (!("Green" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Green"] = 0;
        }
        if (!("Blue" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Blue"] = 0;
        }
        if (!("Alpha" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Alpha"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RGBA instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RGBA}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RGBA(/** @type {Partial<RGBA>} */($$parsedSource));
    }
}

export class TextTheme {
    /**
     * Creates a new TextTheme instance.
     * @param {Partial<TextTheme>} [$$source = {}] - The source object to create the TextTheme.
     */
    constructor($$source = {}) {
        if (!("Text" in $$source)) {
            /**
             * Text is the colour of the text
             * @member
             * @type {number | null}
             */
            this["Text"] = null;
        }
        if (!("Background" in $$source)) {
            /**
             * Background is the background colour of the text
             * @member
             * @type {number | null}
             */
            this["Background"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TextTheme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TextTheme}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TextTheme(/** @type {Partial<TextTheme>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {number}
 */
export const Theme = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * SystemDefault will use whatever the system theme is. The application will follow system theme changes.
     */
    SystemDefault: 0,

    /**
     * Dark Mode
     */
    Dark: 1,

    /**
     * Light Mode
     */
    Light: 2,
};

/**
 * ThemeSettings defines custom colours to use in dark or light mode.
 * They may be set using the hex values: 0x00BBGGRR
 */
export class ThemeSettings {
    /**
     * Creates a new ThemeSettings instance.
     * @param {Partial<ThemeSettings>} [$$source = {}] - The source object to create the ThemeSettings.
     */
    constructor($$source = {}) {
        if (!("DarkModeActive" in $$source)) {
            /**
             * Dark mode active window
             * @member
             * @type {WindowTheme | null}
             */
            this["DarkModeActive"] = null;
        }
        if (!("DarkModeInactive" in $$source)) {
            /**
             * Dark mode inactive window
             * @member
             * @type {WindowTheme | null}
             */
            this["DarkModeInactive"] = null;
        }
        if (!("LightModeActive" in $$source)) {
            /**
             * Light mode active window
             * @member
             * @type {WindowTheme | null}
             */
            this["LightModeActive"] = null;
        }
        if (!("LightModeInactive" in $$source)) {
            /**
             * Light mode inactive window
             * @member
             * @type {WindowTheme | null}
             */
            this["LightModeInactive"] = null;
        }
        if (!("DarkModeMenuBar" in $$source)) {
            /**
             * Dark mode MenuBar
             * @member
             * @type {MenuBarTheme | null}
             */
            this["DarkModeMenuBar"] = null;
        }
        if (!("LightModeMenuBar" in $$source)) {
            /**
             * Light mode MenuBar
             * @member
             * @type {MenuBarTheme | null}
             */
            this["LightModeMenuBar"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ThemeSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ThemeSettings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType12;
        const $$createField1_0 = $$createType12;
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType12;
        const $$createField4_0 = $$createType14;
        const $$createField5_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("DarkModeActive" in $$parsedSource) {
            $$parsedSource["DarkModeActive"] = $$createField0_0($$parsedSource["DarkModeActive"]);
        }
        if ("DarkModeInactive" in $$parsedSource) {
            $$parsedSource["DarkModeInactive"] = $$createField1_0($$parsedSource["DarkModeInactive"]);
        }
        if ("LightModeActive" in $$parsedSource) {
            $$parsedSource["LightModeActive"] = $$createField2_0($$parsedSource["LightModeActive"]);
        }
        if ("LightModeInactive" in $$parsedSource) {
            $$parsedSource["LightModeInactive"] = $$createField3_0($$parsedSource["LightModeInactive"]);
        }
        if ("DarkModeMenuBar" in $$parsedSource) {
            $$parsedSource["DarkModeMenuBar"] = $$createField4_0($$parsedSource["DarkModeMenuBar"]);
        }
        if ("LightModeMenuBar" in $$parsedSource) {
            $$parsedSource["LightModeMenuBar"] = $$createField5_0($$parsedSource["LightModeMenuBar"]);
        }
        return new ThemeSettings(/** @type {Partial<ThemeSettings>} */($$parsedSource));
    }
}

/**
 * WebviewGpuPolicy values used for determining the webview's hardware acceleration policy.
 * @readonly
 * @enum {number}
 */
export const WebviewGpuPolicy = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * WebviewGpuPolicyAlways Hardware acceleration is always enabled.
     */
    WebviewGpuPolicyAlways: 0,

    /**
     * WebviewGpuPolicyOnDemand Hardware acceleration is enabled/disabled as request by web contents.
     */
    WebviewGpuPolicyOnDemand: 1,

    /**
     * WebviewGpuPolicyNever Hardware acceleration is always disabled.
     */
    WebviewGpuPolicyNever: 2,
};

export class WindowTheme {
    /**
     * Creates a new WindowTheme instance.
     * @param {Partial<WindowTheme>} [$$source = {}] - The source object to create the WindowTheme.
     */
    constructor($$source = {}) {
        if (!("BorderColour" in $$source)) {
            /**
             * BorderColour is the colour of the window border
             * @member
             * @type {number | null}
             */
            this["BorderColour"] = null;
        }
        if (!("TitleBarColour" in $$source)) {
            /**
             * TitleBarColour is the colour of the window title bar
             * @member
             * @type {number | null}
             */
            this["TitleBarColour"] = null;
        }
        if (!("TitleTextColour" in $$source)) {
            /**
             * TitleTextColour is the colour of the window title text
             * @member
             * @type {number | null}
             */
            this["TitleTextColour"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowTheme instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowTheme}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowTheme(/** @type {Partial<WindowTheme>} */($$parsedSource));
    }
}

export class WindowsWindow {
    /**
     * Creates a new WindowsWindow instance.
     * @param {Partial<WindowsWindow>} [$$source = {}] - The source object to create the WindowsWindow.
     */
    constructor($$source = {}) {
        if (!("BackdropType" in $$source)) {
            /**
             * Select the type of translucent backdrop. Requires Windows 11 22621 or later.
             * Only used when window's `BackgroundType` is set to `BackgroundTypeTranslucent`.
             * Default: Auto
             * @member
             * @type {BackdropType}
             */
            this["BackdropType"] = BackdropType.$zero;
        }
        if (!("DisableIcon" in $$source)) {
            /**
             * Disable the icon in the titlebar
             * Default: false
             * @member
             * @type {boolean}
             */
            this["DisableIcon"] = false;
        }
        if (!("Theme" in $$source)) {
            /**
             * Theme (Dark / Light / SystemDefault)
             * Default: SystemDefault - The application will follow system theme changes.
             * @member
             * @type {Theme}
             */
            this["Theme"] = Theme.$zero;
        }
        if (!("CustomTheme" in $$source)) {
            /**
             * Specify custom colours to use for dark/light mode
             * Default: nil
             * @member
             * @type {ThemeSettings}
             */
            this["CustomTheme"] = (new ThemeSettings());
        }
        if (!("DisableFramelessWindowDecorations" in $$source)) {
            /**
             * Disable all window decorations in Frameless mode, which means no "Aero Shadow" and no "Rounded Corner" will be shown.
             * "Rounded Corners" are only available on Windows 11.
             * Default: false
             * @member
             * @type {boolean}
             */
            this["DisableFramelessWindowDecorations"] = false;
        }
        if (!("WindowMask" in $$source)) {
            /**
             * WindowMask is used to set the window shape. Use a PNG with an alpha channel to create a custom shape.
             * Default: nil
             * @member
             * @type {string}
             */
            this["WindowMask"] = "";
        }
        if (!("WindowMaskDraggable" in $$source)) {
            /**
             * WindowMaskDraggable is used to make the window draggable by clicking on the window mask.
             * Default: false
             * @member
             * @type {boolean}
             */
            this["WindowMaskDraggable"] = false;
        }
        if (!("ResizeDebounceMS" in $$source)) {
            /**
             * ResizeDebounceMS is the amount of time to debounce redraws of webview2
             * when resizing the window
             * Default: 0
             * @member
             * @type {number}
             */
            this["ResizeDebounceMS"] = 0;
        }
        if (!("WindowDidMoveDebounceMS" in $$source)) {
            /**
             * WindowDidMoveDebounceMS is the amount of time to debounce the WindowDidMove event
             * when moving the window
             * Default: 0
             * @member
             * @type {number}
             */
            this["WindowDidMoveDebounceMS"] = 0;
        }
        if (!("EventMapping" in $$source)) {
            /**
             * Event mapping for the window. This allows you to define a translation from one event to another.
             * Default: nil
             * @member
             * @type {{ [_ in events$0.WindowEventType]?: events$0.WindowEventType }}
             */
            this["EventMapping"] = {};
        }
        if (!("HiddenOnTaskbar" in $$source)) {
            /**
             * HiddenOnTaskbar hides the window from the taskbar
             * Default: false
             * @member
             * @type {boolean}
             */
            this["HiddenOnTaskbar"] = false;
        }
        if (!("EnableSwipeGestures" in $$source)) {
            /**
             * EnableSwipeGestures enables swipe gestures for the window
             * Default: false
             * @member
             * @type {boolean}
             */
            this["EnableSwipeGestures"] = false;
        }
        if (!("Menu" in $$source)) {
            /**
             * Menu is the menu to use for the window.
             * @member
             * @type {Menu | null}
             */
            this["Menu"] = null;
        }
        if (!("Permissions" in $$source)) {
            /**
             * Permissions map for WebView2. If empty, default permissions will be granted.
             * @member
             * @type {{ [_ in CoreWebView2PermissionKind]?: CoreWebView2PermissionState }}
             */
            this["Permissions"] = {};
        }
        if (!("ExStyle" in $$source)) {
            /**
             * ExStyle is the extended window style
             * @member
             * @type {number}
             */
            this["ExStyle"] = 0;
        }
        if (!("GeneralAutofillEnabled" in $$source)) {
            /**
             * GeneralAutofillEnabled enables general autofill
             * @member
             * @type {boolean}
             */
            this["GeneralAutofillEnabled"] = false;
        }
        if (!("PasswordAutosaveEnabled" in $$source)) {
            /**
             * PasswordAutosaveEnabled enables autosaving passwords
             * @member
             * @type {boolean}
             */
            this["PasswordAutosaveEnabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowsWindow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowsWindow}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType15;
        const $$createField5_0 = $Create.ByteSlice;
        const $$createField9_0 = $$createType6;
        const $$createField12_0 = $$createType1;
        const $$createField13_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("CustomTheme" in $$parsedSource) {
            $$parsedSource["CustomTheme"] = $$createField3_0($$parsedSource["CustomTheme"]);
        }
        if ("WindowMask" in $$parsedSource) {
            $$parsedSource["WindowMask"] = $$createField5_0($$parsedSource["WindowMask"]);
        }
        if ("EventMapping" in $$parsedSource) {
            $$parsedSource["EventMapping"] = $$createField9_0($$parsedSource["EventMapping"]);
        }
        if ("Menu" in $$parsedSource) {
            $$parsedSource["Menu"] = $$createField12_0($$parsedSource["Menu"]);
        }
        if ("Permissions" in $$parsedSource) {
            $$parsedSource["Permissions"] = $$createField13_0($$parsedSource["Permissions"]);
        }
        return new WindowsWindow(/** @type {Partial<WindowsWindow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Menu.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = RGBA.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = u$0.Var.createFrom($Create.Any);
const $$createType5 = MacTitleBar.createFrom;
const $$createType6 = $Create.Map($Create.Any, $Create.Any);
const $$createType7 = MacWebviewPreferences.createFrom;
const $$createType8 = MacLiquidGlass.createFrom;
const $$createType9 = TextTheme.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = WindowTheme.createFrom;
const $$createType12 = $Create.Nullable($$createType11);
const $$createType13 = MenuBarTheme.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = ThemeSettings.createFrom;
const $$createType16 = $Create.Map($Create.Any, $Create.Any);
